/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiV1TeamConfigRouteImport } from './routes/api/v1/team-config'
import { Route as ApiV1DeviceDisconnectRouteImport } from './routes/api/v1/device/disconnect'
import { Route as ApiV1DeviceCheckInRouteImport } from './routes/api/v1/device/check-in'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TeamConfigRoute = ApiV1TeamConfigRouteImport.update({
  id: '/api/v1/team-config',
  path: '/api/v1/team-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DeviceDisconnectRoute = ApiV1DeviceDisconnectRouteImport.update({
  id: '/api/v1/device/disconnect',
  path: '/api/v1/device/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DeviceCheckInRoute = ApiV1DeviceCheckInRouteImport.update({
  id: '/api/v1/device/check-in',
  path: '/api/v1/device/check-in',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/developers': typeof DevelopersRoute
  '/setup': typeof SetupRoute
  '/api/v1/team-config': typeof ApiV1TeamConfigRoute
  '/api/v1/device/check-in': typeof ApiV1DeviceCheckInRoute
  '/api/v1/device/disconnect': typeof ApiV1DeviceDisconnectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/developers': typeof DevelopersRoute
  '/setup': typeof SetupRoute
  '/api/v1/team-config': typeof ApiV1TeamConfigRoute
  '/api/v1/device/check-in': typeof ApiV1DeviceCheckInRoute
  '/api/v1/device/disconnect': typeof ApiV1DeviceDisconnectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/developers': typeof DevelopersRoute
  '/setup': typeof SetupRoute
  '/api/v1/team-config': typeof ApiV1TeamConfigRoute
  '/api/v1/device/check-in': typeof ApiV1DeviceCheckInRoute
  '/api/v1/device/disconnect': typeof ApiV1DeviceDisconnectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/developers'
    | '/setup'
    | '/api/v1/team-config'
    | '/api/v1/device/check-in'
    | '/api/v1/device/disconnect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/developers'
    | '/setup'
    | '/api/v1/team-config'
    | '/api/v1/device/check-in'
    | '/api/v1/device/disconnect'
  id:
    | '__root__'
    | '/'
    | '/developers'
    | '/setup'
    | '/api/v1/team-config'
    | '/api/v1/device/check-in'
    | '/api/v1/device/disconnect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevelopersRoute: typeof DevelopersRoute
  SetupRoute: typeof SetupRoute
  ApiV1TeamConfigRoute: typeof ApiV1TeamConfigRoute
  ApiV1DeviceCheckInRoute: typeof ApiV1DeviceCheckInRoute
  ApiV1DeviceDisconnectRoute: typeof ApiV1DeviceDisconnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/team-config': {
      id: '/api/v1/team-config'
      path: '/api/v1/team-config'
      fullPath: '/api/v1/team-config'
      preLoaderRoute: typeof ApiV1TeamConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/device/disconnect': {
      id: '/api/v1/device/disconnect'
      path: '/api/v1/device/disconnect'
      fullPath: '/api/v1/device/disconnect'
      preLoaderRoute: typeof ApiV1DeviceDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/device/check-in': {
      id: '/api/v1/device/check-in'
      path: '/api/v1/device/check-in'
      fullPath: '/api/v1/device/check-in'
      preLoaderRoute: typeof ApiV1DeviceCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevelopersRoute: DevelopersRoute,
  SetupRoute: SetupRoute,
  ApiV1TeamConfigRoute: ApiV1TeamConfigRoute,
  ApiV1DeviceCheckInRoute: ApiV1DeviceCheckInRoute,
  ApiV1DeviceDisconnectRoute: ApiV1DeviceDisconnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
